org: ieeeutec
service: api-alumnos

provider:
  name: aws
  runtime: python3.13
  memorySize: 256
  timeout: 20
  iam:
    role: arn:aws:iam::535557349201:role/LabRole

functions:
  listar:
    handler: ListarAlumnos.lambda_handler
    events:
      - http:
          path: /alumnos/listar
          method: post
          cors: true
          integration: lambda-proxy # ✅ CAMBIADO

  crear:
    handler: CrearAlumno.lambda_handler
    events:
      - http:
          path: /alumnos/crear
          method: post
          cors: true
          integration: lambda-proxy # ✅ CAMBIADO

  buscar:
    handler: BuscarAlumno.lambda_handler
    events:
      - http:
          path: /alumnos/buscar
          method: post
          cors: true
          integration: lambda-proxy # ✅ CAMBIADO

  modificar:
    handler: ModificarAlumno.lambda_handler
    events:
      - http:
          path: /alumnos/modificar
          method: put
          cors: true
          integration: lambda-proxy # ✅ CAMBIADO

  eliminar:
    handler: EliminarAlumno.lambda_handler
    events:
      - http:
          path: /alumnos/eliminar
          method: delete
          cors: true
          integration: lambda-proxy # ✅ CAMBIADO
