org: ieeeutec
service: api-alumnos

provider:
  name: aws
  runtime: python3.12
  timeout: 30
  iam:
    role: arn:aws:iam::535557349201:role/LabRole

functions:
  listar:
    handler: ListarAlumnos.lambda_handler
    events:
      - http:
          path: /alumnos/listar
          method: post
          cors: true
          # ← QUITAR 'integration: lambda' (usa Proxy por defecto)
  
  crear:
    handler: CrearAlumno.lambda_handler
    events:
      - http:
          path: /alumnos/crear
          method: post
          cors: true
          # ← QUITAR 'integration: lambda'
  
  buscar:
    handler: BuscarAlumno.lambda_handler
    events:
      - http:
          path: /alumnos/buscar
          method: post
          cors: true
          # ← QUITAR 'integration: lambda'
  
  modificar:
    handler: ModificarAlumno.lambda_handler
    events:
      - http:
          path: /alumnos/modificar
          method: put
          cors: true
          # ← QUITAR 'integration: lambda'
  
  eliminar:
    handler: EliminarAlumno.lambda_handler
    events:
      - http:
          path: /alumnos/eliminar
          method: delete
          cors: true
          # ← QUITAR 'integration: lambda'
